### ISSUE TITLE
[Docs] Components / Tooltip

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit#114]
Should follow the structure below:
---
# Component name

Introduction paragraph - purpose, useage, value.
### Base Title
- Description - purpose and function
- Code snippet (make sure this is fully valid and accessible HTML)
  (repeat as necessary)
### Modifier Title
- Description - purpose and usage
- Code snippet (make sure this is fully valid and accessible HTML)
  (repeat as necessary)
### State Title
- Description - purpose and usage
- Code snippet (make sure this is fully valid and accessible HTML)
  (repeat as necessary)

**Comment by joebell93** [comment]
@aaronthomas please can you pick this up soon? This issue's been up for a while now

**Comment by aaronthomas** [comment]
# Tooltip

Provides contextual information and can be invoked from any node. Can be triggered either on hover or on click. 

## Base

**Standard Tooltip**

The tooltip appears as white box below the trigger. When active, the tooltip whitewashes the entire viewport.

The tooltip trigger can be any node – a button, link, icon, anything. In this example we use a simple `c-btn` component.

By default, the tooltip is meant to be triggered on click. You can do this by toggling the stateful `is-active` class from the `c-tooltip` component.


    <div class="c-tooltip is-active">
      <button class="c-btn c-btn--primary c-tooltip__trigger">Trigger tooltip</button>
      <div class="c-tooltip__content">
          This is some text inside a tooltip.
      </div>
    </div>
## Modifiers

**Hoverable Tooltip**

Tooltips can also be triggered on the `:hover` state of the trigger, rather than click by applying the `c-tooltip--hover` modifier to the component.

When using the hover modifier, the viewport is not whitewashed.


    <div class="c-tooltip c-tooltip--hover">
      <button class="c-btn c-btn--primary c-tooltip__trigger">Trigger tooltip</button>
      <div class="c-tooltip__content">
          This is some text inside a tooltip.
      </div>
    </div>

**Right aligned**

By default, tooltips are aligned to the right. In some use cases, you may need the tooltip to be aligned to the right to avoid overflow. This can be enabled by adding the `c-tooltip--right`  modifier to the component.


    <div class="c-tooltip c-tooltip--right">
      <button class="c-btn c-btn--primary c-tooltip__trigger">Trigger tooltip</button>
      <div class="c-tooltip__content">
          This is some text inside a tooltip.
      </div>
    </div>

**Comment by joebell93** [comment]
Awesome, cheers @aaronthomas 🎉

**Comment by joebell93** [comment]
sky.com/toolkit/components/tooltip
