### ISSUE TITLE
Facilitate theming

### ISSUE THREAD

**Issue by steveduffin** [sky-uk/toolkit#296]
Provide a standardised approach to theming with minimal overhead.

Toolkit should influence how it's users implement theming in their apps but without the burden of maintaining several different brands that are likely to be in a state of flux.

Current use cases:

**Sky VIP (Loyalty)**
- Four distinct colour treatments of components for different tiers

**Sky Mobile** 
- Text gradients for features - mix, sync etc
- Modifier on tile to add "glint"

**Sky Talk**
- Text gradient  

Suggested approach to follow

**Comment by joebell93** [comment]
Just leaving my thoughts here for further discussion tomorrow

UI is a disposable global layer, that's the whole point of it being separate from the Core. So for me, it makes more sense for brand-specific UI layers to be owned in a package controlled by the appropriate team, not in this repository.

Toolkit is our **global** library, not the home of everything.
Opening it up to everything immediately risks the stability of our project due to sudden changes in brand-specific marketing.

![image](https://user-images.githubusercontent.com/7349341/31377886-78031078-ada1-11e7-99dd-18988a2c1b2e.png)

---

In terms of an approach though, I definitely agree we need to advise/facilitate a scalable solution. Interested to see what you suggest

**Comment by steveduffin** [comment]
Started a feature branch to allow us to experiment with proposed solution: https://github.com/sky-uk/brand/tree/feature/setup

**Comment by joebell93** [comment]
Awesome, I know this is currently WIP but when we do use `npm` can I suggest we use the private group as well as prefix with `brand-`?

e.g. `@sky-uk/brand-loyalty` etc

**Comment by steveduffin** [comment]
@StefanMcCready and I had a few pairing sessions planned that I had to bail on. Hoping to pick this back up now I've got more capacity

**Comment by joebell93** [comment]
What's the latest update on this @steveduffin?

**Comment by steveduffin** [comment]
Very low priority for me ATM. Suggest we close until the need arises again, unless there's any volunteers to continue?

**Comment by joebell93** [comment]
I'll close this for now but absolutely feel free to open again when you've got the time @steveduffin
