### ISSUE TITLE
Trim Gradients 

### ISSUE THREAD

**Issue by steveduffin** [sky-uk/toolkit#479]
In trading we are seeing a whole slew of new gradients in what we are calling a "trim" - a small band applied to card like UI - Broadband, talk and TV products. 

Are they global enough to live alongside the toolkit gradients? If not, they still need to live in a common area.

We also need a way to reverse the horizontal direction

**Comment by Salstar24** [comment]
So according to this Slack thread, we have had the go-ahead that these should be global: https://sky.slack.com/archives/C0L5RS99S/p1547562678008100

And @StefanMcCready was just telling me that these might work well as a new set of Toolkit classes - so that anyone can just add:

```
<div className="u-trim-gradient--name-of-gradient"></div>
```

to the bottom of their component. (Did I get the naming conventions right...?) 

Alternatively, <Trim /> could become it's own atom, which could accept a particular gradient name as a prop?? Is that overkill?

**Comment by steveduffin** [comment]
So far with gradients it's worked well having a map and mixin combo to generate gradients and then components using this to generate as needed. 

Potentially we take this further with having some kind of abstracted theme class but this would be a sizable change of direction so maybe one we revisit

**Comment by steveduffin** [comment]
Fixed by #481
